# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserData', '0003_user_fplist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeaderOrder', models.CharField(max_length=255)),
                ('UserAgent_in_the_request', models.TextField(default='')),
                ('AcceptType', models.TextField(default='')),
                ('AcceptEncoding', models.CharField(max_length=128)),
                ('AcceptLanguage', models.CharField(max_length=32)),
                ('IPAddress', models.GenericIPAddressField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('DNT', models.BooleanField(default=False)),
                ('User_Agent_obtained_by_JS', models.TextField(default='')),
                ('OS', models.CharField(default='', max_length=20)),
                ('OS_Version', models.CharField(default='', max_length=32)),
                ('Browser', models.CharField(default='', max_length=32)),
                ('BrowserVersion', models.CharField(default='', max_length=50)),
                ('ScreenResolution', models.CharField(default='', max_length=50)),
                ('AvailableViewArea', models.CharField(default='', max_length=50)),
                ('ZoomRatio', models.FloatField(default=0.0)),
                ('AspectRation', models.FloatField(default=0.0)),
                ('Plugins', models.TextField(default='')),
                ('Font', models.TextField(default='')),
                ('TimeZone', models.CharField(default='', max_length=16)),
                ('FlashEnabled', models.BooleanField(default=False)),
                ('CookiesEnabled', models.BooleanField(default=False)),
                ('Flash_Version', models.CharField(default='', max_length=32)),
                ('Color_Depth', models.IntegerField(default=0)),
                ('Language', models.CharField(default='', max_length=10)),
                ('Canvas', models.TextField(default='')),
                ('FingerPrint', models.BigIntegerField(default=0)),
                ('browserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserData.User')),
            ],
        ),
    ]
