# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finger_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='AcceptLanguage',
            field=models.CharField(max_length=128),
        ),
    ]
