# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finger_db', '0002_auto_20170731_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='FingerPrint',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='AspectRation',
            field=models.FloatField(default=0.0),
        ),
    ]
