# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0002_auto_20170801_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='FPList',
            field=models.TextField(default=''),
        ),
    ]
